/**
 * @File Name          : MSN_WorkStepAnswerTriggerHandler.cls
 * @Description        : Trigger Handler for WorkStepAnswer__c
 * @Author             : David Azzi
 * @Group              : 
 * @Last Modified By   : David Azzi
 * @Last Modified On   : 13/01/2022
 * @Modification Log   : 
 * Ver      Date            Author                  Modification
 * 1.0      01/12/2021      David Azzi              Initial Version
**/
public class MSN_WorkStepAnswerTriggerHandler {
    // comment the handler out because there is no function in it
    // implements ITriggerHandler{
    // Allows unit tests (or other code) to disable this trigger for the transaction
    // public static Boolean TriggerDisabled = false;
    
    /*
        Checks to see if the trigger has been disabled either by custom setting or by running code
    */
    /*public Boolean IsDisabled()
    {
        return false;
    }
    
    public void BeforeInsert(List<SObject> newItems) 
    {
    }
    
    public void BeforeUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) 
    {
    } 
    public void BeforeDelete(Map<Id, SObject> oldItems) {}  
    public void AfterInsert(Map<Id, SObject> newItems) {}      
    public void AfterUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) {} 
    public void AfterDelete(Map<Id, SObject> oldItems) {} 
    public void AfterUndelete(Map<Id, SObject> oldItems) {}*/
}